const mongoose = require('mongoose');

const url = process.env.MONGODB_URI;
mongoose.connect(url, { useNewUrlParser: true, useUnifiedTopology: true });

const personSchema = new mongoose.Schema({
  name: String,
  number: String,
  id: Number,
});

const Person = mongoose.model('Person', personSchema);

if (process.argv.length === 3) {
  console.log('Phonebook:');
  Person.find({}).then((result) => {
    result.forEach((person) => {
      console.log(`${person.name} ${person.number}`);
    });
    mongoose.connection.close();
  });
} else if (process.argv.length < 5) {
  console.log('Person name or phonenumber missing from the command line arguments');
  process.exit();
} else if (process.argv.length === 5) {
  const person = new Person({
    name: process.argv[3],
    number: process.argv[4],
    // Id gets autogenerated by the DB
  });

  person.save().then(() => {
    console.log(`Added ${person.name} number ${person.number} to phonebook`);
    mongoose.connection.close();
  });
} else if (process.argv.length > 5) {
  console.log('Too many command line arguments given! Make sure to use quotation marks when inserting names!');
  process.exit();
} else {
  console.log('Unknown error');
  process.exit();
}
